# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_text', models.CharField(default='No Tweet Data. Weird.', max_length=140)),
                ('sent_rating', models.DecimalField(decimal_places=10, max_digits=19)),
                ('keyword_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='canary.Keyword')),
            ],
        ),
    ]
