# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canary', '0002_auto_20170313_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='keyword_id',
            new_name='keyword',
        ),
    ]
