# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canary', '0003_auto_20170313_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='keyword',
            new_name='search_keyword',
        ),
    ]
