# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canary', '0005_auto_20170313_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkeyword',
            name='keyword_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
