# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canary', '0006_auto_20170315_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='origin',
            field=models.CharField(default='No Location data. Weird.', max_length=140),
        ),
    ]
