# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canary', '0007_tweet_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='origin',
            field=models.CharField(default='No Location data. Weird.', max_length=140, null=True),
        ),
    ]
